name: "TextNow Autosend"
on:
  push: # 触发机制为push操作
    branches: main
  workflow_dispatch:
    
  schedule: # 触发机制为定时任务
    - cron: "44 4 * * *" # 每天4点44分自动执行
    - cron: "44 16 * * *" # 每天16点44分自动执行
jobs:
  autosend:
    runs-on: ubuntu-latest # 运行环境为最新的Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 使用官方提供的checkout 2.0版本获取代码
      - name: Setup node.js
        uses: actions/setup-node@v1 # 使用官方提供的setup-node 1.0版本配置node环境
        with:
          node-version: "12.x" # 使用node 12版本作为运行环境
      - name: Install dependencies
        run: npm install # 安装依赖
      - name: Run autosend
        env:
          TEXTNOW_USERNAME: ${{secrets.TEXTNOW_USERNAME}} # 获取并设置定义好的用户名环境变量值
          TEXTNOW_PASSWORD: ${{secrets.TEXTNOW_PASSWORD}} # 获取并设置定义好的用户密码环境变量值
          TEXTNOW_RECIPIENT: ${{secrets.TEXTNOW_RECIPIENT}} # 获取并设置定义好的接收方的电话号码环境变量值
          TEXTNOW_MESSAGE: ${{secrets.TEXTNOW_MESSAGE}} # 获取并设置定义好的发送的信息内容环境变量值
        run: |
          node index.js
