name: "TextNow Auto-send"
on:
  push:
    branches: main
  workflow_dispatch:

  schedule:
    - cron: "44 16 * * *"
jobs:
  autosend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
        run: npm install
      - name: Cache multi paths
        uses: actions/cache@v2
        with:
          path: |
            .cache
            ~/.cache
          key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }}
          restore-keys: ${{ secrets.CACHE_NAME }}-
      - name: Run autosend
        uses: mujo-code/puppeteer-headful@master
        env:
          TEXTNOW_USERNAME: ${{secrets.TEXTNOW_USERNAME}}
          TEXTNOW_PASSWORD: ${{secrets.TEXTNOW_PASSWORD}}
          TEXTNOW_COOKIES: ${{secrets.TEXTNOW_COOKIES}}
          TEXTNOW_RECIPIENT: ${{secrets.TEXTNOW_RECIPIENT}}
          TEXTNOW_MESSAGE: ${{secrets.TEXTNOW_MESSAGE}}
          CAPTCHA_TOKEN: ${{secrets.CAPTCHA_TOKEN}}
        with:
          args: npm start
